indir: no  # to be overriden in CLI
outdir: no  # to be overriden in CLI
category: no
detect_model: no
detect_threthold: no

model:
  path: no  # to be overriden in CLI
  checkpoint: best.ckpt

dataset:
  kind: default
  img_suffix: .png
  pad_out_to_modulo: 8

device: cuda
out_key: inpainted
